name: Pages

on:

  push:

    branches:

      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies

        run: pip install -r requirements.txt

      - name: Build site

        run: jekyll build

      - name: Deploy site

        uses: peaceiris/gh-pages@v3

        with:

          deploy_branch: gh-pages

          publish_dir: ./public
